version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
      
  AfterInstall:
    - location: scripts/initialize.sh
      runas: root
  
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
 

