name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
    

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./PrJava
      
    steps:
      - name: CheckOut
      - uses: actions/checkout@v3
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        working-directory: ${{env.working-directory}}

      - name: Build with Gradle
        run: ./gradlew bootjar
        shell: bash
        working-directory: ${{env.working-directory}}

